#-------------------------------------------
# CITS3002 Project 2019
# Author: Alexander Varano della Vergiliana
# Student ID: 22268701
#-------------------------------------------

CC	=	gcc
CFLAGS	=	-std=c99
TARGET	=	gameserver

all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c

clean:
	$(RM) $(TARGET)
